export const GET_POKE_SUCCESS = 'GET_POKE_SUCCESS';
export const GET_POKE_NEXT_SUCCESS = 'GET_POKE_NEXT_SUCCESS';
export const GET_POKE_PREVIUS_SUCCESS = 'GET_POKE_PREVIUS_SUCCESS';
export const GET_DETAILS_POKEMON = 'GET_DETAILS_POKEMON';
